// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cglwhyeqzflstkjxuagk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnbHdoeWVxemZsc3Rranh1YWdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxOTc5NDMsImV4cCI6MjA2Mjc3Mzk0M30.NarMtHkQoYcDE6KRYcU-y5ehMah9R7RMv7sCITrPySM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);